### ISSUE TITLE
[FEAT] Search화면 디자인 컴포넌트 제작

### ISSUE THREAD

**Issue by indianaPoly** [yourssu/Soomsil-Web#10]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
검색 TF의 디자인 컴포넌트 제작 (RealTimeKeyword)

## Figma View
작업하시는 내용의 피그마 이미지를 첨부해주세요
<img width="228" alt="스크린샷 2024-02-01 오후 2 59 34" src="https://github.com/yourssu/Soomsil-Web/assets/95522176/84f5f35a-2ad3-4270-a4e8-59563c5be840">

## TODO
- [ ] 해당 키워드 눌리면 검색 결과 호출 및 검색 결과 검색창에 있어야 함.
- [ ] 반응형에 상관없이 사이즈 동일하므로 1개의 사이즈만 고려해서 제작
- [ ] 시간 표시 부분 (아래 자세히 작성)
 

## ETC
- BE에서 1~6시간의 통계를 수집한다고 했으나 결과 처리 및 몇 분 단위로 데이터를 주는지에 대해서는 명확히 나온 부분이 없어, 추후 수정할게 생기지 않을까 싶습니다!
- 시간 표시 부분을 서버로 부터 데이터를 보내달라고 할지 혹은 데이터를 가지고 오는 시간에 맞춰서 프론트 측에서 처리할지 고민 중..
