### ISSUE TITLE
[FEAT] 서랍장 상세 페이지 API 연결

### ISSUE THREAD

**Issue by nijuy** [yourssu/Soomsil-Web#107]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
- 서랍장 서비스 1개 클릭했을 때 뜨는 상세 페이지 API 연결하기

## Swagger View
![image](https://github.com/yourssu/Soomsil-Web/assets/87255462/45febd9b-d464-4211-814c-4f14e29fae21)
![image](https://github.com/yourssu/Soomsil-Web/assets/87255462/538dae15-8a21-44a1-b704-64114fa951e6)

## TODO
- [x] ProductDetailResponse 타입 생성
- [x] ProductDetailResult 타입 생성
- [x] 상세 정보 가져오는 api 함수 만들기
- [x] 상세 정보 가져오는 훅 만들기
- [x] 띄우기

- [x] 제작자의 서비스 가져오는 api 함수 만들기
- [x] 훅 만들기
- [x] 띄우기

**Comment by nijuy** [comment]
url 3개밖에 없는데 webpageUrl 추가한다고 하심
