### ISSUE TITLE
[FIX] 실시간 검색어 API 관련 수정

### ISSUE THREAD

**Issue by intersoom** [yourssu/Soomsil-Web#120]
# ISSUE ✅ : FIX

## 📖 DESCRIPTION
백엔드 검색 모듈이 수정에 따른 프론트엔드 수정건입니다.

## TODO
- [x] endpoint 수정 (`topQuery` → `topQueries`)
- [x] 응답 데이터의 속성명 수정 (`data.query` → `data.queries`)
- [x] baseUrl .env 파일로 수정

## ETC
기타사항
