### ISSUE TITLE
[FEAT] 공통 에러 처리

### ISSUE THREAD

**Issue by nijuy** [yourssu/Soomsil-Web#130]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
ErrorBoundary를 사용한 공통 에러 처리
(로그인 401은 포함 ❌)

## Figma View
로지가 만들어준 폴백 컴포넌트

![image](https://github.com/yourssu/Soomsil-Web/assets/87255462/0f9c8d8e-2753-409b-9375-37115def52cb)

## TODO
- [x] src/search/component의 ErrorBoundary를 react-error-boundary의 ErrorBoundary로 교체
- [x] router.tsx 최상단을 ErrorBoundary로 감싸기
- [x] DrawerLayout.tsx 내의 Outlet을 ErrorBoundary로 감싸기 (헤더, 푸터 유지하고 content 영역만 fallback 띄우려고)
- [x] Fallback 컴포넌트 만들기
