### ISSUE TITLE
[REFACTOR] 서랍장 UI 버그 수정, 코드 리팩토링 

### ISSUE THREAD

**Issue by nijuy** [yourssu/Soomsil-Web#131]
# ISSUE ✅ : REFACTOR

## 📖 DESCRIPTION
자잘한 코드 리팩토링

## Figma View
화면상의 변경은 없음

## TODO
- [x] Category 컴포넌트 “카테고리 유형” 텍스트에 스타일 입히기 (지금은 그냥 div로 되어있음)
- [x] 상세 페이지 이미지 사이즈 관련 수정
- [x] 중복 타입 정리
    - product.type.ts의 ProductResult와 ProductList.type.ts의 Product
    - product.type.ts의 ProductResponses와 ProductList.type.ts의 ProductListResponses ➡ 는 체리가 #124에서 해줌
- [x] `EmptyScreen` 컴포넌트 리팩토링
    - 문구를 empty.constant.ts에 정의하고 쓰기 때문에 굳이 props로 전달하지 않고 type만 넘기면 `EmptyScreen` 내에서 상수를 가져다 쓰도록 수정할 수 있을 거 같음

- [x] 상세 페이지의 이미지가 Header를 침범하지 않게 z-index 수정
  <img width="1440" alt="323642442-c20ab651-94df-45b5-96e8-b4262e5159cd" src="https://github.com/yourssu/Soomsil-Web/assets/87255462/67d5fbb2-1ad3-45ca-8804-35e9bd5f9127">

- [x] CategoryDropdown 클릭 범위 제한 (Star ranking 위쪽을 클릭해도 열린다는 제보)

![image](https://github.com/yourssu/Soomsil-Web/assets/87255462/572c6c32-f384-4012-bc99-5650e1716cda)

## ETC
기타사항
