### ISSUE TITLE
[FEAT] 회원가입 퍼블리싱 (UI 및 예외처리) 구현

### ISSUE THREAD

**Issue by fecapark** [yourssu/Soomsil-Web#134]
# ISSUE ✅ : 회원가입 퍼블리싱 (UI 및 예외처리) 구현

## 📖 DESCRIPTION

회원가입 페이지에 들어갈 컴포넌트들의 UI를 구현하고 예외처리를 구현합니다.

## Figma View

![1](https://github.com/yourssu/Soomsil-Web/assets/101973955/7c548bf6-9ad7-4897-8d8e-274dd203a055)
![2](https://github.com/yourssu/Soomsil-Web/assets/101973955/41c7d57e-de58-46e7-b239-62b3f0ac91b0)
![3](https://github.com/yourssu/Soomsil-Web/assets/101973955/1ef983d0-c4ab-436b-a8c6-752561ab4688)
![4](https://github.com/yourssu/Soomsil-Web/assets/101973955/e844109c-dc86-463e-819a-13252fa02e86)
![5](https://github.com/yourssu/Soomsil-Web/assets/101973955/c0bce4d4-5022-4ed1-ae79-d479928b0329)
![6](https://github.com/yourssu/Soomsil-Web/assets/101973955/fdd1859e-b3a9-4ed2-aa61-9a8c92bdad62)
![7](https://github.com/yourssu/Soomsil-Web/assets/101973955/fc1b0416-f697-46b8-84d3-726e0d060789)

## TODO
- [x] 약관동의 페이지 (필수 체크시 다음 활성화)
- [x] 이메일 인증 받기 (잘못된 형태의 이메일 인증시 인증 불가)
- [x] 이메일 인증 확인 (시간 초과시 인증 불가)
- [x] 닉네임 / 비밀번호 설정 (잘못된 폼 입력시 회원가입 불가)
- [x] 회원가입 완료 (완료 시 어디로 리다이렉트 될 것인지는 슬랙 확인해야 함 => 로그인 페이지)

## ETC

- 예상 구현 완료 시점 4월 14일 (일)
