### ISSUE TITLE
[FEAT] Home 화면 검색 키워드 컴포넌트 구현

### ISSUE THREAD

**Issue by AAminha** [yourssu/Soomsil-Web#28]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
Home 화면의 검색 키워드 컴포넌트를 구현합니다.

## Figma View
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/6f379670-ed62-4830-9974-fcc3646ce0b8)

## TODO
- [x] 검색 키워드 컴포넌트 구현
  - [x] 일정 기준이 넘어가면 말 줄임표 적용
  - [x] 키워드를 클릭하면 해당 키워드 검색 페이지로 이동

## ETC
기타사항
