### ISSUE TITLE
[FEAT] Home 화면 SNS 컴포넌트 및 홈화면 구성 일부 구현

### ISSUE THREAD

**Issue by AAminha** [yourssu/Soomsil-Web#37]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
Home 화면의 SNS 컴포넌트 및 홈화면 구성을 일부(서랍장 랭킹, 검색 키워드, SNS)를 구현합니다

### SNS 컴포넌트
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/1a449c17-8279-4d64-bee5-9c11fc9af6b6)
### 홈화면 구성 일부
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/c5a6847d-4c49-4338-9eb5-661e392f71ae)

## TODO
- [x] SNS 컴포넌트 구현
  - [x] 각 아이콘에 링크 연결
- [x] 홈화면 구성 일부 구현
  - [x] 서랍장 랭킹 컴포넌트
  - [x] 검색 키워드 컴포넌트
  - [x] SNS 컴포넌트

## ETC
기타사항
