### ISSUE TITLE
[FEAT] Search화면 디자인 컴포넌트 제작

### ISSUE THREAD

**Issue by intersoom** [yourssu/Soomsil-Web#4]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
검색 TF의 디자인 컴포넌트 제작 (searchBar, resultListItem)

## Figma View
<img width="708" alt="스크린샷 2024-01-30 오후 6 47 55" src="https://github.com/yourssu/Soomsil-Web/assets/78731710/ac283e0c-4a7e-4382-aa2c-32de30cfcee2">
<img width="327" alt="스크린샷 2024-01-30 오후 6 48 02" src="https://github.com/yourssu/Soomsil-Web/assets/78731710/7097f9b8-a422-4d4e-90e2-a9d78c364170">

## TODO
- [ ] 검색바 컴포넌트 제작
  - [ ] fixed로 따라오게 제작
  - [x] 반응형 (1920-1620 / 1620-1358 / 1358-720) -> 로고 위치 주의
  - [x] 검색 입력 내용 삭제 기능 제작
  - [ ] 검색 api 요청 함수를 등록할 수 있도록 제작
  - [x] 로고 누르면 홈화면 이동 기능 제작
- [ ] 검색 결과 리스트 아이템 컴포넌트 제작
  - [x] 썸네일 / 제목 / 본문 기준에 맞게 제작
     - 썸네일이 1개일 때는 제목 최대 1줄, 썸네일이 5개일 때는 제목 최대 2줄
     - 본문은 썸네일이 1개일 때는 3줄, 썸네일이 5개일 때는 2줄
## ETC
- 개발하면서 추가사항이 생길 수 있음.. 😞
