### ISSUE TITLE
[REFACTOR] Card 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by nijuy** [yourssu/Soomsil-Web#40]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
서랍장, 홈에서 사용하는 Card 컴포넌트를 뚝딱 고칩니다

## TODO
- [ ] `StyledContainer` Link 말고 다른 컴포넌트로 바꾸기 / https://github.com/yourssu/Soomsil-Web/pull/34#discussion_r1493167739

  - [ ] `CardContainer` 클릭 이벤트 추가하기
- [ ] index.css와 중복으로 정의된 스타일 삭제하기
- [ ] `StyledSettingButton` 높이 수정하기 / https://github.com/yourssu/Soomsil-Web/pull/34#discussion_r1493163850
