### ISSUE TITLE
[FEAT] 링크 유효성 검증 및 등록 페이지 레이아웃 작업

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Soomsil-Web#68]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
4가지 링크 별 유효성을 검증하는 로직을 추가합니다.
유효하지 않은 링크의 경우 validation 디자인을 띄우도록 처리합니다.
서랍장 등록 페이지 전체 레이아웃을 조정합니다.

## Figma View
![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/daee360f-6285-4c77-a3ae-f31f3c68fe73)
|웹|모바일|
|--|--|
|![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/9e724da6-4742-4590-8972-288fdfc7e0b6)|![image](https://github.com/yourssu/Soomsil-Web/assets/84809236/7465e43d-91ef-4252-ab3a-0f7ea98fa954)|

## TODO
- [ ] 링크 유효성 검증 로직 추가
- [ ] validation 디자인 처리
- [ ] 등록 페이지 전체 레이아웃 작업 (+ 모바일 대응)
