### ISSUE TITLE
[FEAT] 홈페이지 API 연결

### ISSUE THREAD

**Issue by AAminha** [yourssu/Soomsil-Web#94]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
홈페이지에 보여지는 서랍장 랭킹, 검색 키워드, 공지사항 API를 연결합니다.

## TODO
- [x] 서랍장 랭킹 API 연결
- [x] 검색 키워드 API 연결
- [x] 공지사항 API 연결

## ETC
기타사항
