### ISSUE TITLE
[REFACTOR] 서치 페이지 코드 개선

### ISSUE THREAD

**Issue by intersoom** [yourssu/Soomsil-Web#98]
# ISSUE ✅ : REFACTOR

## 📖 DESCRIPTION
#86 에서 처리하지 못한 리팩토링 작업을 수행합니다.

## TODO
- [x] FallbackComponent 추상화 작업 [링크](https://github.com/yourssu/Soomsil-Web/pull/86#discussion_r1510367677)
- [x] ResultListItems.tsx 훅 분리 [링크](https://github.com/yourssu/Soomsil-Web/pull/86#discussion_r1510370393)
- [x] ResultListItems 컴포넌트 명 변경
- [x] ~ErrorBoundary -> error로 말고 다른 방법으로 처리하기 (불필요)~
- [x] ~컬러 변경 반영 (버튼 색상 때문에 YDS 반영 후 반영 예정)~
- [x] 시스템 오류 반영

## ETC
QA를 빠르게 진행하기 위해서 따로 이슈를 팠습니다!
